### PR TITLE
Revert "PARQUET-1529: Shade fastutil in all modules where used (#617)"

### PR DESCRIPTION
**Pull request by mccheah**
This reverts commit dcfd53ae1e6c3cc47eec319f2a3394e4fd1ce403.

Workaround for https://issues.apache.org/jira/browse/PARQUET-1544.

### CODE REVIEW

**Comment by mccheah** [comment]
@sjrand @robert3005 for SA. Needed for some Iceberg experimentation, but unsure if this is going to impact anything else that depends on Parquet more generally.

**Comment by mccheah** [comment]
Or @vinooganesh also. I'd like someone to sign off on this before merging, at least walking through the thought experiment on whether or not this revert could break anything.

**Comment by vinooganesh** [comment]
hey @mccheah, I'm not sure I know this code-path well enough to feel comfortable doing the revert. Will let @sjrand @robert3005 weigh in

**Comment by mccheah** [comment]
Favoring #41 instead of this.

**Pull request closed without merging**
